// <auto-generated />
namespace Rowa.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Createsecrettable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createsecrettable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804202301305_Create secret table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
