// <auto-generated />
namespace Rowa.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_To_Remove_Username : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_To_Remove_Username));
        
        string IMigrationMetadata.Id
        {
            get { return "201806131246227_Update_To_Remove_Username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
